/** Véhicules disponibles au Maroc — tarifs journaliers en MAD (dirham marocain). */
export const fleetCars = [
  {
    id: 1,
    name: 'Mercedes-Benz S-Class',
    category: 'Berline luxe',
    city: 'Casablanca',
    priceMAD: 700,
    image: '/car-1.jpg',
    features: ['5 passagers', 'Climatisation bi-zone', 'GPS & WiFi'],
  },
  {
    id: 2,
    name: 'BMW X7',
    category: 'SUV premium',
    city: 'Marrakech',
    priceMAD: 650,
    image: '/car-2.jpg',
    features: ['7 passagers', 'Toit panoramique', 'Cuir & massage'],
  },
  {
    id: 3,
    name: 'Audi A8',
    category: 'Berline executive',
    city: 'Rabat',
    priceMAD: 700,
    image: '/car-3.jpg',
    features: ['5 passagers', 'Suspension pneumatique', 'Bang & Olufsen'],
  },
  {
    id: 4,
    name: 'Range Rover Sport',
    category: 'SUV déluxe',
    city: 'Agadir',
    priceMAD: 550,
    image: '/car-4.jpg',
    features: ['5 passagers', '4WD intelligent', 'Caméra 360°'],
  },
  {
    id: 5,
    name: 'Tesla Model 3',
    category: 'Électrique premium',
    city: 'Tanger',
    priceMAD: 400,
    image: '/car5.webp',
    features: ['Autonomie ~500 km', 'Autopilot', 'Supercharge'],
  },
  {
    id: 6,
    name: 'Toyota Land Cruiser',
    category: '4x4 tout-terrain',
    city: 'Fès',
    priceMAD: 600,
    image: '/car-6.jpg',
    features: ['7 passagers', '4x4 verrouillable', 'Idéal Atlas & pistes'],
  },
  {
    id: 7,
    name: 'Volkswagen Golf 8',
    category: 'Citadine confort',
    city: 'Meknès',
    priceMAD: 300,
    image: '/car-7.jpg',
    features: ['5 passagers', 'Apple CarPlay / Android Auto', 'Faible consommation'],
  },
  {
    id: 8,
    name: 'Dacia Duster',
    category: 'Économique & robuste',
    city: 'Ouarzazate',
    priceMAD: 250,
    image: '/car-8.jpg',
    features: ['5 passagers', 'Coffre spacieux', 'Idéal routes du Sud'],
  },
]
