/** Véhicules disponibles au Maroc — tarifs journaliers en MAD (dirham marocain). */
export const fleetCars = [
  {
    id: 1,
    name: "Mercedes-Benz S-Class",
    category: "Berline luxe",
    city: "Casablanca",
    priceMAD: 700,
    image: "/car-1.jpg",
    features: ["5 passagers", "Climatisation bi-zone", "GPS & WiFi"],
  },
  {
    id: 2,
    name: "BMW X7",
    category: "SUV premium",
    city: "Marrakech",
    priceMAD: 650,
    image: "/car-2.jpg",
    features: ["7 passagers", "Toit panoramique", "Cuir & massage"],
  },
  {
    id: 3,
    name: "Audi A8",
    category: "Berline executive",
    city: "Rabat",
    priceMAD: 700,
    image: "/car-3.jpg",
    features: ["5 passagers", "Suspension pneumatique", "Bang & Olufsen"],
  },
  {
    id: 4,
    name: "Range Rover Sport",
    category: "SUV déluxe",
    city: "Agadir",
    priceMAD: 550,
    image: "/car-4.jpg",
    features: ["5 passagers", "4WD intelligent", "Caméra 360°"],
  },
  {
    id: 5,
    name: "Tesla Model 3",
    category: "Électrique premium",
    city: "Tanger",
    priceMAD: 400,
    image: "/car5.webp",
    features: ["Autonomie ~500 km", "Autopilot", "Supercharge"],
  },
  {
    id: 6,
    name: "Toyota Land Cruiser",
    category: "4x4 tout-terrain",
    city: "Fès",
    priceMAD: 600,
    image: "/car-6.jpg",
    features: ["7 passagers", "4x4 verrouillable", "Idéal Atlas & pistes"],
  },
  {
    id: 7,
    name: "Volkswagen Golf 8",
    category: "Citadine confort",
    city: "Meknès",
    priceMAD: 300,
    image: "/car-7.jpg",
    features: [
      "5 passagers",
      "Apple CarPlay / Android Auto",
      "Faible consommation",
    ],
  },
  {
    id: 8,
    name: "Dacia Duster",
    category: "Économique & robuste",
    city: "Ouarzazate",
    priceMAD: 250,
    image: "/car-8.jpg",
    features: ["5 passagers", "Coffre spacieux", "Idéal routes du Sud"],
  },

  // 🔥 New Cars Added Below

  {
    id: 9,
    name: "Hyundai Tucson",
    category: "SUV moderne",
    city: "Casablanca",
    priceMAD: 350,
    image: "/car-9.jpg",
    features: ["5 passagers", "Écran tactile", "Caméra de recul"],
  },
  {
    id: 10,
    name: "Renault Clio 5",
    category: "Citadine économique",
    city: "Rabat",
    priceMAD: 220,
    image: "/car-10.jpg",
    features: ["5 passagers", "Faible consommation", "Idéal ville"],
  },
  {
    id: 11,
    name: "Peugeot 208",
    category: "Compacte urbaine",
    city: "Marrakech",
    priceMAD: 230,
    image: "/car-11.jpg",
    features: ["5 passagers", "Climatisation", "Bluetooth"],
  },
  {
    id: 12,
    name: "Ford Mustang",
    category: "Sport & prestige",
    city: "Tanger",
    priceMAD: 900,
    image: "/car-12.jpg",
    features: ["4 passagers", "Moteur V8", "Design iconique"],
  },
  {
    id: 13,
    name: "Porsche Cayenne",
    category: "SUV sport luxe",
    city: "Casablanca",
    priceMAD: 1200,
    image: "/car-13.jpg",
    features: ["5 passagers", "Performance sportive", "Intérieur premium"],
  },
  {
    id: 14,
    name: "Kia Sportage",
    category: "SUV familial",
    city: "Agadir",
    priceMAD: 320,
    image: "/car-14.jpg",
    features: ["5 passagers", "Coffre spacieux", "Économie carburant"],
  },
  {
    id: 15,
    name: "Fiat 500",
    category: "Mini citadine",
    city: "Marrakech",
    priceMAD: 180,
    image: "/car-15.jpg",
    features: ["4 passagers", "Compacte", "Idéal centre-ville"],
  },
  {
    id: 16,
    name: "Chevrolet Tahoe",
    category: "SUV grand format",
    city: "Rabat",
    priceMAD: 750,
    image: "/car-16.jpg",
    features: ["7 passagers", "Grand coffre", "Confort longue distance"],
  },
];
